apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - resources:
            requests:
              cpu: 10m
              memory: 400Mi
            limits:
              memory: 400Mi
          env:
          - name: jasypt.encryptor.password
            valueFrom:
              configMapKeyRef:
                key: AUTH_JASYPT_KEY
                name: cloudnine-env
          - name: management.zipkin.tracing.endpoint
            valueFrom:
              configMapKeyRef:
                key: ZIPKIN_URI
                name: cloudnine-env
          - name: eureka.client.service-url.defaultZone
            valueFrom:
              configMapKeyRef:
                key: EUREKA_URI
                name: cloudnine-env
          - name: spring.profiles.active
            value: "dev"
          - name: JAVA_OPS
            value: "-XX:+UseContainerSupport"
          name: auth
          image: fosong98/authservice:1.0.8
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20