apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
  labels:
    app: store
spec:
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - env:
        - name: jasypt.encryptor.password
          valueFrom:
            configMapKeyRef:
              key: STORE_JASYPT_KEY
              name: cloudnine-env
        - name: management.zipkin.tracing.endpoint
          valueFrom:
            configMapKeyRef:
              key: ZIPKIN_URI
              name: cloudnine-env
        - name: eureka.client.service-url.defaultZone
          valueFrom:
            configMapKeyRef:
              key: EUREKA_URI
              name: cloudnine-env
        - name: spring.profiles.active
          value: "dev"
        - name: JAVA_OPS
          value: "-XX:+UseContainerSupport"
        name: store
        image: fosong98/storeservice:1.0.10
        ports:
        - containerPort: 8084

        resources:
          requests:
            cpu: 10m
            memory: 400Mi
          limits:
            memory: 400Mi

        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 20