apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - env:
          - name: management.zipkin.tracing.endpoint
            valueFrom:
              configMapKeyRef:
                key: ZIPKIN_URI
                name: cloudnine-env
          name: eureka
          image: fosong98/eureka:1.0.2
          ports:
            - containerPort: 8761
