apiVersion: v1
kind: Service
metadata:
  name: webpage
  labels:
    app: webpage
spec:
  selector:
    app: webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer