apiVersion: v1
kind: Service
metadata:
  name: credit
  labels:
    app: credit
spec:
  selector:
    app: credit
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
