server:
  port: 8084
  shutdown: graceful

spring:
  application:
    name: store-service
    
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info
    com.c9pay.storeservice: debug
  pattern:
    level: "${hostname}"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${hostname}

jwt:
  secret: ENC(0w2i1G7yrJF9gVt9p6iCVfjBTemAJUUclBnioURXDZDjDC/pQ+nYpaeYtJcM/DnuNbQ+wDwR3hQHgrLHL3JueoEqw1W5nizxMG354d4ql+UlG9bg3Smw3Gn4SO3mN96N1maW1tAWHMqlCI1JXlu4MA==)
  token-validity-in-seconds: ENC(qTkrg7Z4SogjDTOrifYFhA==)
  service-type: ENC(YiQxZD9T0NVa+VjtOI9v0w==)

symmetric:
  key: ENC(uQyOMTCgH+o1qbkAInELKGwd7YbRByK/)



management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3, w3c
      produce: b3, w3c
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"


---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

---

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: ENC(AAPl6FCFDCs6z6qVwV8ZlMO1+56LZDlbAlVkBnURwGSqWPY4eHRo/5Iw+lb8iYRszyuE2mbBldU=)
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari.maximum-pool-size: 3
    url: ENC(wd08NsYoy+CnJKb72l2e15g/X/6nByJj+hZZYRJ2gfHwW/wn/i0k8lOqac90wskNgQ+xBU7ZywW5Bp8RzfYbBu13tPLxzlIJBBfjoUF4gwDdaShMnP6TZWlosdTEg9u+)
    username: ENC(kCC9hb6QCjoM11Hj17ArDlM0egpP/lMp)
    password: ENC(KR14amvV8/xSdwLtsJGM9tgZKnXD6qO7)

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 3
        limitRefreshPeriod: 1s
        timeoutDuration: 2s
